import { Game } from "./gamesSlice"


export const games: Game[] = [
    {
        id: 'cyberpunk-2077',
        title: 'Cyberpunk 2077',
        price: 59.99,
        releaseDate: '9 дек. 2020 г.',
        ageLimit: '17+',
        description: 'Cyberpunk 2077 — приключенческая ролевая игра, действие которой происходит в мегаполисе Найт-Сити, где власть, роскошь и модификации тела ценятся выше всего. Вы играете за V, наёмника в поисках устройства, позволяющего обрести бессмертие. Вы сможете менять киберимпланты, навыки и стиль игры своего персонажа, исследуя открытый мир, где ваши поступки влияют на ход сюжета и всё, что вас окружает.',
        genres: ['Экшены', 'Приключения', 'Ролевые'],
        developers: ['CD PROJEKT RED', 'CD PROJEKT'],
        publishers: ['CD PROJEKT RED'],
        metacriticScore: 73,
        media: {
            poster: '/images/games/cyberpunk-2077/poster.jpg',
            cover: '/images/games/cyberpunk-2077/cover.jpg',
            screenshots: [
                '/images/games/cyberpunk-2077/screenshot1.jpg',
                '/images/games/cyberpunk-2077/screenshot2.jpg',
                '/images/games/cyberpunk-2077/screenshot3.jpg',
                '/images/games/cyberpunk-2077/screenshot4.jpg',
                '/images/games/cyberpunk-2077/screenshot5.jpg',
                '/images/games/cyberpunk-2077/screenshot6.jpg',
            ],
        },
    },
    {
        id: 'grand-theft-auto-v',
        title: 'Grand Theft Auto V',
        price: 29.99,
        releaseDate: '17 сент. 2013 г.',
        ageLimit: '17+',
        description: 'Когда молодой уличный жулик, отставной грабитель банков и опасный для общества психопат оказываются втянуты в разборки с самыми пугающими и сумасшедшими представителями криминального мира, правительства США и индустрии развлечений, им приходится выполнить серию рискованных налетов, чтобы выжить в безжалостном городе, где они не могут доверять никому – и в первую очередь друг другу.',
        genres: ['Экшены', 'Приключения'],
        developers: ['Rockstar North', 'Rockstar Games'],
        publishers: ['Rockstar Games'],
        metacriticScore: 92,
        media: {
            poster: '/images/games/grand-theft-auto-v/poster.jpg',
            cover: '/images/games/grand-theft-auto-v/cover.jpg',
            screenshots: [
                '/images/games/grand-theft-auto-v/screenshot1.jpg',
                '/images/games/grand-theft-auto-v/screenshot2.jpg',
                '/images/games/grand-theft-auto-v/screenshot3.jpg',
                '/images/games/grand-theft-auto-v/screenshot4.jpg',
                '/images/games/grand-theft-auto-v/screenshot5.jpg',
                '/images/games/grand-theft-auto-v/screenshot6.jpg',
            ],
        },
    },
    {
        id: 'detroit-become-human',
        title: 'Detroit: Become Human',
        price: 39.99,
        releaseDate: '25 мая 2018 г.',
        ageLimit: '17+',
        description: 'Детройт, 2038 год. Похожие на людей андроиды стали основной рабочей силой на планете. Они никогда не устают, всегда слушают своих хозяев и никогда не говорят «Нет»... Но однажды все изменилось. Некоторые андроиды начали вести себя не так, как обычно, словно у них появилась способность испытывать чувства... Теперь вам предстоит управлять тремя андроидами, чтобы помочь им понять, кто же они на самом деле. Ваши действия и решения определят их судьбу – а может, даже и будущее всего города.',
        genres: ['Экшены', 'Приключения'],
        developers: ['Quantic Dream'],
        publishers: ['Sony Computer Entertainment', 'Quantic Dream'],
        metacriticScore: 79,
        media: {
            poster: '/images/games/detroit-become-human/poster.jpg',
            cover: '/images/games/detroit-become-human/cover.jpg',
            screenshots: [
                '/images/games/detroit-become-human/screenshot1.jpg',
                '/images/games/detroit-become-human/screenshot2.jpg',
                '/images/games/detroit-become-human/screenshot3.jpg',
                '/images/games/detroit-become-human/screenshot4.jpg',
                '/images/games/detroit-become-human/screenshot5.jpg',
                '/images/games/detroit-become-human/screenshot6.jpg',
            ],
        },
    },
    {
        id: 'little-nightmares',
        title: 'Little Nightmares',
        price: 19.99,
        releaseDate: '27 апр. 2017 г.',
        ageLimit: '',
        description: 'Little Nightmares – это мрачная сказка, которая заставит вас вспомнить свои детские кошмары. Помогите Шестой выбраться из Чрева – странного подводного судна, населенного жуткими существами, которые только и ищут, чем бы поживиться... Вы попадете в страшный кукольный дом, который станет одновременно вашей тюрьмой и игровой площадкой. Разбудите в себе ребенка, дайте простор фантазии и выберитесь на свободу!',
        genres: ['Экшены', 'Приключения', 'Платформеры'],
        developers: ['BANDAI NAMCO Entertainment America', 'Tarsier Studios'],
        publishers: ['Bandai Namco Entertainment', 'BANDAI NAMCO Entertainment US'],
        metacriticScore: 81,
        media: {
            poster: '/images/games/little-nightmares/poster.jpg',
            cover: '/images/games/little-nightmares/cover.jpg',
            screenshots: [
                '/images/games/little-nightmares/screenshot1.jpg',
                '/images/games/little-nightmares/screenshot2.jpg',
                '/images/games/little-nightmares/screenshot3.jpg',
                '/images/games/little-nightmares/screenshot4.jpg',
                '/images/games/little-nightmares/screenshot5.jpg',
                '/images/games/little-nightmares/screenshot6.jpg',
            ],
        },
    },
];