import { Game } from "./gamesSlice"


export const games: Game[] = [
    {
        id: 'cyberpunk-2077',
        title: 'Cyberpunk 2077',
        price: 59.99,
        releaseDate: '9 дек. 2020 г.',
        ageLimit: '18+',
        description: 'Cyberpunk 2077 — приключенческая ролевая игра, действие которой происходит в мегаполисе Найт-Сити, где власть, роскошь и модификации тела ценятся выше всего. Вы играете за V, наёмника в поисках устройства, позволяющего обрести бессмертие. Вы сможете менять киберимпланты, навыки и стиль игры своего персонажа, исследуя открытый мир, где ваши поступки влияют на ход сюжета и всё, что вас окружает.',
        genres: ['Экшены', 'Приключения', 'Ролевые'],
        developers: ['CD PROJEKT RED', 'CD PROJEKT'],
        publishers: ['CD PROJEKT RED'],
        metacriticScore: 86,
        media: {
            poster: '/images/games/cyberpunk-2077/poster.jpg',
            cover: '/images/games/cyberpunk-2077/cover.jpg',
            screenshots: [
                '/images/games/cyberpunk-2077/screenshot1.jpg',
                '/images/games/cyberpunk-2077/screenshot2.jpg',
                '/images/games/cyberpunk-2077/screenshot3.jpg',
                '/images/games/cyberpunk-2077/screenshot4.jpg',
                '/images/games/cyberpunk-2077/screenshot5.jpg',
                '/images/games/cyberpunk-2077/screenshot6.jpg',
            ],
        },
    },
    {
        id: 'grand-theft-auto-v',
        title: 'Grand Theft Auto V',
        price: 29.99,
        releaseDate: '17 сент. 2013 г.',
        ageLimit: '18+',
        description: 'Когда молодой уличный жулик, отставной грабитель банков и опасный для общества психопат оказываются втянуты в разборки с самыми пугающими и сумасшедшими представителями криминального мира, правительства США и индустрии развлечений, им приходится выполнить серию рискованных налетов, чтобы выжить в безжалостном городе, где они не могут доверять никому – и в первую очередь друг другу.',
        genres: ['Экшены', 'Приключения'],
        developers: ['Rockstar North', 'Rockstar Games'],
        publishers: ['Rockstar Games'],
        metacriticScore: 97,
        media: {
            poster: '/images/games/grand-theft-auto-v/poster.jpg',
            cover: '/images/games/grand-theft-auto-v/cover.jpg',
            screenshots: [
                '/images/games/grand-theft-auto-v/screenshot1.jpg',
                '/images/games/grand-theft-auto-v/screenshot2.jpg',
                '/images/games/grand-theft-auto-v/screenshot3.jpg',
                '/images/games/grand-theft-auto-v/screenshot4.jpg',
                '/images/games/grand-theft-auto-v/screenshot5.jpg',
                '/images/games/grand-theft-auto-v/screenshot6.jpg',
            ],
        },
    },
    {
        id: 'detroit-become-human',
        title: 'Detroit: Become Human',
        price: 39.99,
        releaseDate: '25 мая 2018 г.',
        ageLimit: '18+',
        description: 'Детройт, 2038 год. Похожие на людей андроиды стали основной рабочей силой на планете. Они никогда не устают, всегда слушают своих хозяев и никогда не говорят «Нет»... Но однажды все изменилось. Некоторые андроиды начали вести себя не так, как обычно, словно у них появилась способность испытывать чувства... Теперь вам предстоит управлять тремя андроидами, чтобы помочь им понять, кто же они на самом деле. Ваши действия и решения определят их судьбу – а может, даже и будущее всего города.',
        genres: ['Экшены', 'Приключения'],
        developers: ['Quantic Dream'],
        publishers: ['Sony Computer Entertainment', 'Quantic Dream'],
        metacriticScore: 78,
        media: {
            poster: '/images/games/detroit-become-human/poster.jpg',
            cover: '/images/games/detroit-become-human/cover.jpg',
            screenshots: [
                '/images/games/detroit-become-human/screenshot1.jpg',
                '/images/games/detroit-become-human/screenshot2.jpg',
                '/images/games/detroit-become-human/screenshot3.jpg',
                '/images/games/detroit-become-human/screenshot4.jpg',
                '/images/games/detroit-become-human/screenshot5.jpg',
                '/images/games/detroit-become-human/screenshot6.jpg',
            ],
        },
    },
    {
        id: 'little-nightmares',
        title: 'Little Nightmares',
        price: 19.99,
        releaseDate: '27 апр. 2017 г.',
        ageLimit: '16+',
        description: 'Little Nightmares – это мрачная сказка, которая заставит вас вспомнить свои детские кошмары. Помогите Шестой выбраться из Чрева – странного подводного судна, населенного жуткими существами, которые только и ищут, чем бы поживиться... Вы попадете в страшный кукольный дом, который станет одновременно вашей тюрьмой и игровой площадкой. Разбудите в себе ребенка, дайте простор фантазии и выберитесь на свободу!',
        genres: ['Экшены', 'Приключения', 'Платформеры'],
        developers: ['BANDAI NAMCO Entertainment America', 'Tarsier Studios'],
        publishers: ['Bandai Namco Entertainment', 'BANDAI NAMCO Entertainment US'],
        metacriticScore: 78,
        media: {
            poster: '/images/games/little-nightmares/poster.jpg',
            cover: '/images/games/little-nightmares/cover.jpg',
            screenshots: [
                '/images/games/little-nightmares/screenshot1.jpg',
                '/images/games/little-nightmares/screenshot2.jpg',
                '/images/games/little-nightmares/screenshot3.jpg',
                '/images/games/little-nightmares/screenshot4.jpg',
                '/images/games/little-nightmares/screenshot5.jpg',
                '/images/games/little-nightmares/screenshot6.jpg',
            ],
        },
    },
    {
        id: 'dying-light',
        title: 'Dying Light',
        price: 29.99,
        releaseDate: '27 янв. 2015 г.',
        ageLimit: '18+',
        description: 'Dying Light - это боевик от первого лица с элементами выживания, действие которого разворачиваются в постапокалиптическом мире, кишащем кровожадными зомби. Изучите город, уничтоженный загадочным вирусом: собирайте ресурсы, создавайте оружие и сражайтесь с полчищами мутантов.',
        genres: ['Экшены', 'Приключения', 'Ролевые'],
        developers: ['Techland'],
        publishers: ['Warner Bros. Interactive'],
        metacriticScore: 74,
        media: {
            poster: '/images/games/dying-light/poster.jpg',
            cover: '/images/games/dying-light/cover.jpg',
            screenshots: [
                '/images/games/dying-light/screenshot1.jpg',
                '/images/games/dying-light/screenshot2.jpg',
                '/images/games/dying-light/screenshot3.jpg',
                '/images/games/dying-light/screenshot4.jpg',
                '/images/games/dying-light/screenshot5.jpg',
                '/images/games/dying-light/screenshot6.jpg',
            ],
        },
    },
    {
        id: 'the-escapists',
        title: 'The Escapists',
        price: 7.99,
        releaseDate: '12 февр. 2015 г.',
        ageLimit: '12+',
        description: 'Вы снова оказались в тюрьме, и ваш единственный шанс — придумать, как сбежать, используя любые средства. Вам решать, как это будет сделано. Может, устроить тюремный бунт? Или выкопать тоннель под тюремными стенами? Или украсть форму охранника, чтобы смешаться с тюремщиками? The Escapists — это уникальное погружение в тюремную среду, где можно создать множество предметов и сочетать их, отважно борясь за обретение свободы. Жизнь в тюрьме заставит вас быть начеку, помня о строгих правилах, которые придется нарушить. Охранники постараются пресечь любые попытки побега, поэтому постарайтесь не вызывать подозрений и являйтесь на перекличку, работайте и прячьте украденные материалы. Побеги — то, что вам удается лучше всего. Вам придется продемонстрировать свои навыки в непростых условиях тюрем всего света.',
        genres: ['Экшены', 'Приключения', 'Ролевые', 'Стратегии', 'Симуляторы', 'Головоломки'],
        developers: ['Team17 Digital', 'Mouldy Toof Studios'],
        publishers: ['Team17 Digital'],
        metacriticScore: 74,
        media: {
            poster: '/images/games/the-escapists/poster.jpg',
            cover: '/images/games/the-escapists/cover.jpg',
            screenshots: [
                '/images/games/the-escapists/screenshot1.jpg',
                '/images/games/the-escapists/screenshot2.jpg',
                '/images/games/the-escapists/screenshot3.jpg',
                '/images/games/the-escapists/screenshot4.jpg',
                '/images/games/the-escapists/screenshot5.jpg',
                '/images/games/the-escapists/screenshot6.jpg',
            ],
        },
    },
    {
        id: 'the-dark-pictures-anthology-little-hope',
        title: 'The Dark Pictures Anthology: Little Hope',
        price: 14.99,
        releaseDate: '29 окт. 2020 г.',
        ageLimit: '18+',
        description: '4 студента и профессор застряли в заброшенном городе Литтл Хоуп и пытаются скрыться от демонов, которые неустанно преследуют их в непроходимом тумане.',
        genres: ['Экшены', 'Приключения'],
        developers: ['Supermassive Games'],
        publishers: ['Bandai Namco Entertainment', 'BANDAI NAMCO Entertainment Europe'],
        metacriticScore: 71,
        media: {
            poster: '/images/games/the-dark-pictures-anthology-little-hope/poster.jpg',
            cover: '/images/games/the-dark-pictures-anthology-little-hope/cover.jpg',
            screenshots: [
                '/images/games/the-dark-pictures-anthology-little-hope/screenshot1.jpg',
                '/images/games/the-dark-pictures-anthology-little-hope/screenshot2.jpg',
                '/images/games/the-dark-pictures-anthology-little-hope/screenshot3.jpg',
                '/images/games/the-dark-pictures-anthology-little-hope/screenshot4.jpg',
                '/images/games/the-dark-pictures-anthology-little-hope/screenshot5.jpg',
                '/images/games/the-dark-pictures-anthology-little-hope/screenshot6.jpg',
            ],
        },
    },
    {
        id: 'papers-please',
        title: 'Papers, Please',
        price: 6.29,
        releaseDate: '7 авг. 2013 г.',
        ageLimit: '17+',
        description: 'Поздравляем! Подведены итоги октябрьской лотереи рабочих мест! Вы - победитель! Немедленно обратитесь в Министерство въезда на пропускном пункте Грештин, чтобы вступить в должность. Вашей семье будет предоставлена квартира в Восточном Грештине, в жилом доме 8 класса. Слава Арстотцке! Война между коммунистической Астотцкой и соседней Колечией, длившаяся шесть лет, только что закончилась, и в результате Арстотцка сумела вернуть себе принадлежащую ей по праву половину пограничного города Грештина. Вы - инспектор иммиграционной службы, ваша задача - контролировать поток лиц, въезжающих в Арстотцку из Колечии через Грештин. Среди толп иммигрантов, надеющихся найти в стране работу, и прочих визитеров скрываются контрабандисты, шпионы и террористы. В вашем распоряжении есть только документы, предоставляемые въезжающими, и незатейливые системы проверки, досмотра и снятия отпечатков пальцев, установленные Министерством въезда. С этим небогатым арсеналом вам предстоит решать, кого можно впустить в Арстотцку, кому следует отказать, а кто подлежит аресту.',
        genres: ['Приключения', 'Симуляторы', 'Образовательные', 'Головоломки'],
        developers: ['3909', 'Lucas Pope', 'Dukope1'],
        publishers: ['3909'],
        metacriticScore: 85,
        media: {
            poster: '/images/games/papers-please/poster.jpg',
            cover: '/images/games/papers-please/cover.jpg',
            screenshots: [
                '/images/games/papers-please/screenshot1.jpg',
                '/images/games/papers-please/screenshot2.jpg',
                '/images/games/papers-please/screenshot3.jpg',
                '/images/games/papers-please/screenshot4.jpg',
                '/images/games/papers-please/screenshot5.jpg',
                '/images/games/papers-please/screenshot6.jpg',
            ],
        },
    },
];